[project]
name = "keratorch-package"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "keratorch",
]

[tool.uv.sources]
keratorch = { path = "keratorch", editable = true }
